### ISSUE TITLE
Broken Link at NLP API docs

### ISSUE THREAD

**Issue by KapilGahlot** [GoogleCloudPlatform/google-cloud-node#2593] opened 2017-09-05 15:02 UTC
Trying to click on the link to get the structure of the sentence attribute in the response results in page not found. 

Here is the page where broken link is located:

https://googlecloudplatform.github.io/google-cloud-node/#/docs/language/0.11.0/language/v1beta2/data_types?method=AnnotateTextResponse

The broken link is 
https://googlecloudplatform.github.io/google-cloud-node/#/docs/language/0.11.0/Data%20Types%2Fv%2Fdata_types?method=Sentence

Thanks

**Comment by stephenplusplus** [comment] 2017-09-05 17:02
Thanks for reporting. I'm going to call this a duplicate of #2590-- the fix to that will address this as well.

Sorry for the trouble.

**Closed by stephenplusplus** 2017-09-05 17:02 UTC
Labels: api: language, docs, type: bug
