### ISSUE TITLE
When the logging library has a failure the callback is never called. 

### ISSUE THREAD

**Issue by Binarytales** [GoogleCloudPlatform/google-cloud-node#1954] opened 2017-02-02 10:56 UTC
When the logging library has a failure the callback is never called. The same is true from the promiseified version. Below is basic sample code with garbage credentials, but I have seen the same issue with seemingly valid credentials and unknown failures.

#### Environment details
  - OS: OS X 10.11.6
  - Node.js version: 6.9.1
  - npm version: 3.10.8
  - google-cloud-node version: @google-cloud/logging@0.6.1

#### Steps to reproduce
```js
var logging = require('@google-cloud/logging')({
    projectId: 'projectx',
    keyFilename: false
});

var syslog = logging.log('syslog');

var metadata = {
  resource: {
    type: 'global',
  }
};

var entry = syslog.entry(metadata, {
  logMsg: 'something happened'
});

syslog.write(entry, function(err, resp) {
  console.log(err, resp);
});
```

I've tried stepping through the code to debug the the root cause of the issue but get stuck when `grpc` starts calling into native code blocks (`call.startBatch`)

**Comment by stephenplusplus** [comment] 2017-02-02 18:55
Please try upgrading to the latest version of `google-cloud` or `@google-cloud/logging`.

**Comment by stephenplusplus** [comment] 2017-02-04 17:16
This is likely a duplicate of #1946. Please follow along there. Thank you and sorry for the trouble.

**Closed by stephenplusplus** 2017-02-04 17:16 UTC
Labels: bug, logging
