### ISSUE TITLE
Datastore request takes longer using Node client library

### ISSUE THREAD

**Issue by cezzy** [GoogleCloudPlatform/google-cloud-node#2108] opened 2017-03-20 06:13 UTC
There is an 80 second delay just before the entity is logged to the console when trying to send datastore request using Node SDK while the exact same request using Python client library just works quickly as expected. See [1] for the Node.js example for fetching an entity from Google Cloud Datastore.

Take note that the same thing happens for creating a new Datastore entity. Can you please advise why this happens for Node.js considering that it works accordingly with other client libraries?

Link:
[1] https://gist.github.com/bennettrogers/ef85afa3f04558da17e71c6ae758dc80

**Comment by stephenplusplus** [comment] 2017-03-20 07:11
The owner of the gist posted some more info here, connecting the delay to the auth library:  https://github.com/stephenplusplus/google-auto-auth/issues/13. It has not been investigated yet.

**Comment by cezzy** [comment] 2017-03-20 07:31
Thank you! This is actually for the same person. We can have it tracked in the original thread instead.

**Comment by lukesneeringer** [comment] 2017-03-20 16:13
@cezzy Thanks for reporting! Closing as a duplicate of stephenplusplus/google-auto-auth#13.

**Closed by lukesneeringer** 2017-03-20 16:13 UTC
