### ISSUE TITLE
Pub/Sub on appengine reports upstream prematurely closed connection

### ISSUE THREAD

**Issue by grandmore** [GoogleCloudPlatform/google-cloud-node#1965] opened 2017-02-06 12:59 UTC
When I deploy to appengine using `gcloud app deploy` the app deploys but it does not connect to PubSub. It just hangs for several minutes then eventually reports an error in the logs.

`"[error] 32#32: *5096 upstream prematurely closed connection while reading response header from upstream, client: 130.211.1.75, server: , request: "GET /permissions HTTP/1.1", upstream: "http://172.18.0.2:8080/permissions", host: "xxxx.appspot.com"" `

I manually created an new app inside the `google cloud shell` to test and the new one works correctly with the same [testSubscriptionPermissions](https://cloud.google.com/pubsub/docs/access_control) code.

1. The new project was based on the node.js `helloworld` example .
2. It was modified using the `google cloud shell` 
3. It was manual launched with `npm start`

I can then access the endpoint `https://8080-dot-2251668-dot-devshell.appspot.com/permissions`, and Pub/Sub words correctly

It feels like a permissions issue but I cannot find any reference to this in the docs. Since it is deployed in google I assume it does not need to be configured any more than:

```
const pubsub = gcloud.pubsub({
  projectId: 'my-project-id'
});
```

I did try adding a keyfile.json but with no success.

Is there any specific way to test for what is wrong or is this something specific to appengine deploys?

Any help would be greatly appreciated.

**Comment by grandmore** [comment] 2017-02-06 16:01
Just want to report that dropping the gcloud version to 0.45 resolved the issue. 

It seems the issue is related to the already reported issues [1955 API requests hang indefinitely](#1955) etc and not permissions as I originally thought.

**Comment by stephenplusplus** [comment] 2017-02-06 17:58
Yes, I believe this is a duplicate of that issue. Please follow along over there, and if it's not connected, we can re-open here.

**Closed by stephenplusplus** 2017-02-06 17:58 UTC
