### ISSUE TITLE
Recognize stream freezes (from example in official docs)

### ISSUE THREAD

**Issue by bloodcarter** [GoogleCloudPlatform/google-cloud-node#1893] opened 2016-12-20 15:25 UTC
Steps to reproduce:
wget https://cloud.google.com/speech/docs/samples/audio.raw
./recognize.js stream audio.raw

**Comment by stephenplusplus** [comment] 2016-12-20 15:26
Dupe of #1892

**Closed by stephenplusplus** 2016-12-20 15:26 UTC
