### ISSUE TITLE
Google Pubsub not responding when deployed to Google App Engine

### ISSUE THREAD

**Issue by edmund-lee** [GoogleCloudPlatform/google-cloud-node#1963] opened 2017-02-04 02:12 UTC
#### Environment details

  - OS: Google App Engine
  - Node.js version: >=4.3.2
  - npm version: 
  - google-cloud/pubsub version: 0.7.0

#### Steps to reproduce

Use the steps and source code outlined in the tutorial below,
https://cloud.google.com/appengine/docs/flexible/nodejs/writing-and-responding-to-pub-sub-messages

Pubsub client api not responding when deployed to Google App Engine.
Works fine when the same code is run on local machine.

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by stephenplusplus** [comment] 2017-02-04 17:16
This is likely a duplicate of #1946. Please follow along there. Thank you and sorry for the trouble.

**Closed by stephenplusplus** 2017-02-04 17:16 UTC
