### ISSUE TITLE
Spanner node.js client used with GCP Functions generates errors when GCP Function is cold

### ISSUE THREAD

**Issue by 8357753** [GoogleCloudPlatform/google-cloud-node#2489] opened 2017-07-24 20:52 UTC
#### Environment details

  - OS:  GCP Functions
  - Node.js version:  GCP Functions
  - npm version: 5.0.3
  - google-cloud-node version: google-cloud/spanner 0.7.1

#### Steps to reproduce

  1. Deploy a GCP Function that uses the Spanner node.js client to run transactions against a Spanner database
  2. Invoke the function and ensure that the function correctly issues the transaction
  3. Wait for 10 min or so and invoke the function and an error occurs 
  4. Immediately invoke the function again and the function correctly issues the transaction

I am initializing the JS client using these instructions i.e. no special config options:
"https://cloud.google.com/spanner/docs/getting-started/nodejs/"

The errors are:
database.run
Error: Endpoint read failed","error_code":14,"query":"SELECT
Error: Session not found: projects/REDACTED/instances/lc-data/databases/lc-data-uat/sessions/AFZejKDAPJhREDACTEDYnFRwi7iMjT0_","error_code":5,"query":"SELECT

database.runTransaction
Error: Endpoint read failed","error_code":14
connection error'"

**Comment by stephenplusplus** [comment] 2017-07-24 20:54
I believe this is a duplicate of #2438, which I see you've posted in. I mean duplicate in the sense that a resolution to that will also resolve this. I'm going to close under that assumption, but please let me know if I'm mistaken and we will re-open.

**Comment by 8357753** [comment] 2017-07-24 20:57
Yep I opened this because the other issue concerned logging so I thought I should make the issue clearer.

**Comment by 8357753** [comment] 2017-07-24 22:32
But this may not be a duplicate, I don't really know. We use Stackdriver logging in other GCP functions without issue and even with this issue we don't always receive "Endpoint read failed" we sometimes get "Session not found". I was thinking that the connection to Spanner was made but perhaps using an orphaned session i.e. an old one passivated with the container when it went cold. Having said that we also get the same issue with a new deployment i.e. fails first time and then works second time. The first time is very quick and the second time slow which makes me think that the first is not using the new container.

**Comment by 8357753** [comment] 2017-07-24 23:41
Also if I delete the Spanner database and then re-create it I get similar errors and these can only be fixed by re-deploying the GCP Function.

**Comment by stephenplusplus** [comment] 2017-07-25 13:38
I'll re-open and maybe @vkedia / @callmehiphop can weigh in.

**Comment by callmehiphop** [comment] 2017-07-25 15:43
We have an open issue for the Session not found (#2061). However if you're redeploying, I don't think it would use sessions from an earlier deployment.

I haven't seen any errors involving re-creating databases, could you post any error messages you get when trying to do so?

**Comment by 8357753** [comment] 2017-07-25 19:55
This morning I came in and ran the functions a few times via Postman and had no problems i.e. they ran fine from cold. I continued and eventually received:

Error: Endpoint read failed","error_code":14

I then redeployed and immediately ran the functions and had no problems. I then manually ran the functions several times and eventually received:

textPayload:  "Function execution took 55 ms, finished with status: 'connection error'"   

I left the functions for 10 min and then ran them and had no problems. I continued and eventually received:

Error: Endpoint read failed","error_code":14

After the error I ran the functions a few times via Postman and had no problems.

Next I deleted and re-created the database and immediately ran the functions and received:

textPayload:  "Function execution took 129 ms, finished with status code: 500"   

I continued and some functions started to work but were very slow >10sec and others continued to fail with error:

"error":"Error: Database not found: projects/REDACTED/instances/REDACTED/databases/REDACTED","error_code":5

I gave up eventually and re-deployed all functions and immediately ran the functions and received:

textPayload:  "Function execution took 343 ms, finished with status: 'connection error'"

After the error I ran the functions a few times via Postman and had no problems.

**Comment by 8357753** [comment] 2017-07-25 20:13
Looked at #2061 but we are using GCP Functions so keep alive is not relevant. But I realise I need to call database.close to stop orphaned sessions being used by a cold function.

**Comment by vkedia** [comment] 2017-07-25 20:22
When the GCP function is invoked multiple times does it recreate the spanner client each time (specifically the `instance` object) or can it reuse them?
Also note that when a database is deleted all its sessions get invalidated. A general advise will be to redeploy your code in that case.

**Comment by 8357753** [comment] 2017-07-25 22:56
Well we could cache the Spanner client (we do so with other logic) but I imagine that would cause issues when the function is cold since the session would be orphaned. 

Using Spanner 0.5.0 (downgraded from 0.7.1 but will test that later) with require('@google-cloud/spanner') at the top of the module but the client, instance and database initialized in the code just before calling 'database.runTransaction' and with 'database.close' called we still get errors:
Error: Endpoint read failed","error_code":14

Moving 'require('@google-cloud/spanner')' to the code just before calling 'database.runTransaction' seems to fix the issues -> In our Postman test suite Functions with this change are now reliable whereas Functions without this change still randomly fail.

It would be great if the Spanner client had a 'nocache' config option for use with Functions, maybe we would only need that in dev environments but maybe not since there will always be Functions that are not used that often.

Current reliable code:

exports.insert = function (record) {
      let spanner;
      if (Config.is_local_dev_mode()) {
        spanner = require('@google-cloud/spanner')({projectId: Config.GCP_PROJECT_ID});
      } else {
        spanner = require('@google-cloud/spanner')();
      }
      const instance = spanner.instance(Config.GCP_SPANNER_INSTANCE_ID);
      const database = instance.database(Config[Config.ENV].GCP_SPANNER_DATABASE_ID);

      .... wrapped with a database.close ...
      database.runTransaction(function(err, tx) {
      .... wrapped with a database.close ...

**Comment by 8357753** [comment] 2017-07-25 23:06
Makes me think that perhaps a transactional store is not a good fit for GCP Functions/AWS Lambdas (at least ones used infrequently) because of the natural overhead of the session, a session that is not needed when using a NoSQL database, horses for courses I guess...

**Comment by 8357753** [comment] 2017-07-25 23:19
Well I spoke too soon, just received a 500 error from the function that seemed to have become reliable and nothing reported in Stackdriver just after the function started. I waited 5 min before running it again and see the entry 'Function execution started' for the new invocation but no 'Function execution took 678 ms, finished with status' entry for the previous function that failed.

**Comment by 8357753** [comment] 2017-07-26 00:07
Random errors seem to be the following i.e. don't see "Endpoint read failed" anymore: 
payload:  "Function execution took 3137 ms, finished with status: 'connection error'"

**Comment by 8357753** [comment] 2017-07-26 03:17
If I use 'database.close' it causes all subsequent calls to the function to fail with the following error but only for transactions involving several inserts:

payload: "Function execution took 3137 ms, finished with status: 'connection error'"

**Comment by 8357753** [comment] 2017-07-26 08:38
So I moved all the Spanner initialization code to a module which caches the logic and removed the 'database.close' calls. Now Spanner is only initialized once for as long as the container is re-used. I still get the occasional 'connection error' after the function has been cold for along time but only in a function that runs several inserts in a transaction, other functions that do simpler calls to Spanner are fine. I have also added logic to retry failed calls to Spanner in order to recover from 'Endpoint read failed' and 'Session not found' errors. I will also put a queue in front of all this in order to also leverage the retry logic from that. 

BTW I have GRPC_TRACE and GRPC_VERBOSITY set and I see verbose debugging information when running locally but none of that information ends up in Stackdriver when the function runs in GCP.

**Comment by landrito** [comment] 2017-08-07 20:44
> I still get the occasional 'connection error' after the function has been cold for along time but only in a function that runs several inserts in a transaction

@vkedia Do you have an idea what could be causing this to happen?

**Comment by 8357753** [comment] 2017-08-07 20:55
These errors are also still happening and not just when the Functions are cold. 

1) connection error
2) Error: Endpoint read failed","error_code":14" 
3) "error":"Error: Database not found: projects/REDACTED/instances/REDACTED/databases/REDACTED","error_code":5

**Comment by lukesneeringer** [comment] 2017-08-08 04:58
@landrito If I understand correctly from a skim, essentially the issue is that the client object is being shared between different GCF instances, but since network connections do not work that way (you can not serialize a connection and send it across the wire), you end up in a wonky state.

The fix is to either not permit client objects to be serialized and shared (like what Python does) or to ensure that the connection object is dropped on serialization and able to be reinitialized on reload.

**Comment by lukesneeringer** [comment] 2017-10-27 21:04
This issue was moved to googleapis/nodejs-spanner#20

**Closed by lukesneeringer** 2017-10-27 21:04 UTC
Labels: api: spanner, priority: p1, status: acknowledged, type: bug

**Comment by ChrisBartonLC** [comment] 2017-11-08 07:39
@stephenplusplus I have pinned to version 0.14.0 of the PubSub client library and this issue does not occur so somewhere between that version and 0.14.5 CloudFunction support has broken. BTW issue #2489 is > 3 months old and PubSub was working a month ago so this may or may not be related.

**Comment by stephenplusplus** [comment] 2017-11-08 14:45
Locking the issue just to make sure we funnel all useful info to one place (https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2438).
