### ISSUE TITLE
Link to EntityMention in the v1beta2 Entity documentation results in a NotFound.

### ISSUE THREAD

**Issue by crunk1** [GoogleCloudPlatform/google-cloud-node#2590] opened 2017-09-04 21:11 UTC
This is an issue with the online documentation.

There is a link to EntityMention in:
https://googlecloudplatform.github.io/google-cloud-node/#/docs/language/0.11.0/language/v1beta2/data_types?method=Entity

The link address is:
https://googlecloudplatform.github.io/google-cloud-node/#/docs/language/0.11.0/Data%20Types%2Fv%2Fdata_types?method=EntityMention

But it redirects to the Not Found page:
https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.56.0/not-found

**Comment by crunk1** [comment] 2017-09-04 21:23
Actually, I think there are quite a few links that are broken. The link to TextSpan in the EntityMention documentation is broken as well.

**Comment by stephenplusplus** [comment] 2017-10-10 21:44
Closing as a duplicate of #2546

**Closed by stephenplusplus** 2017-10-10 21:44 UTC
Labels: api: language, docs, type: bug
