### ISSUE TITLE
Error: Received RST_STREAM with error code 2

### ISSUE THREAD

**Issue by lafama** [GoogleCloudPlatform/google-cloud-node#2619] opened 2017-09-19 06:05 UTC
#### Environment details

  - OS: darwin x64
  - Node.js version:8.5.0
  - npm version:5.4.2
  - google-cloud/pubsub version:0.14.1

#### Steps to reproduce

  1. require `google-cloud/pubsub`
  2. 
`subscription=pubsub.topic('awesomeTopic).subscription('awesomeTopicSubcription',{reuseExisting: true})`
   3. 
```
subscription.on('error',function(error){
    logger.error('subscription',error);
  })
```
 4. This (3) will log the following 
```
{"message":"subscription",
"stack":"Error: Received RST_STREAM with error code 2\n    at ClientDuplexStream.<anonymous> 
(/app/node_modules/@google-cloud/pubsub/src/connection-pool.js:218:21)\n    
at emitOne (events.js:115:13)\n    at ClientDuplexStream.emit (events.js:210:7)\n    
at ClientDuplexStream._emitStatusIfDone (/app/node_modules/grpc/src/node/src/client.js:260:10)\n    
at ClientDuplexStream._receiveStatus (/app/node_modules/grpc/src/node/src/client.js:233:8)\n    
at /app/node_modules/grpc/src/node/src/client.js:757:12","code":13,"timestamp":"2017-09-19T04:57:56.510Z",
"level":"error"}
```

**Comment by callmehiphop** [comment] 2017-09-19 16:52
@lafama thanks for reporting. I believe this already being investigated, but this message is almost always received when the PubSub api closes a stream. However we usually retry on that specific error, so I'm intrigued as to why you're seeing it.

I'm unable to reproduce with the steps you've provided, so if you could provide us with a gist/repo/etc. that reproduces the error you're seeing, that would help tremendously.

**Comment by lafama** [comment] 2017-09-19 18:51
What would make PubSub api closes a stream? My worker process hangs after this error and i have to keep restarting it. The challenge reproducing this is that it occurs infrequently and at random time in production. It also only stated when upgrade to 0.14.0 from 0.13.0

**Comment by callmehiphop** [comment] 2017-09-19 19:28
The streaming API is new, hence why this only occurs in 0.14.x. Prior to this release we manually polled the servers.

Usually the PubSub API closes the stream after about 30 minutes. However, the only time we would emit an error like this would be if the client was unable to re-establish a connection within 5 minutes of the previous connections closing. So it might be that the server closes the connection and won't allow for any new connections. @jganetsk for thoughts here.

If that turns out to be the case, then you might want to consider re-creating the subscription object when that error fires, possibly with a backoff of some kind.

**Comment by jganetsk** [comment] 2017-09-20 15:53
Is there some way to confirm that the user is experiencing a prolonged absence of connectivity, and that's why the error is occurring? Maybe the client library's error handling code has a bug.

**Comment by callmehiphop** [comment] 2017-09-20 20:35
@jganetsk I think you're right, after investigating it seems that the `metadata` event does not always fire, which is what I was using to see if the stream connected. I'm thinking instead we should just check that the channel is connected and assume that when creating a stream it'll just work. Does that sound correct to you?

**Comment by jganetsk** [comment] 2017-09-20 20:51
I don't know these details. I trust you and @lukesneeringer can work them out.

**Comment by lafama** [comment] 2017-09-21 09:06
This error seems to occur exactly 34 minutes into processing. So i have to restart my worker process every 34th Minute..

**Comment by callmehiphop** [comment] 2017-09-23 00:02
@lafama I'm working on resolving this, however in the mean time I would suggest downgrading to 0.13.

**Comment by lafama** [comment] 2017-09-23 13:13
Downgraded to 0.13.1. Works for now, @callmehiphop update me, when the issue is fixed

**Comment by callmehiphop** [comment] 2017-09-25 14:15
@lafama I've opened a PR (#2627) that I believe will address the issue you are seeing. Would you mind testing it?

**Comment by lafama** [comment] 2017-09-26 06:02
@callmehiphop this PR seems to work fine, so far in tests no errors are being logged and the process is not hanging 👍

**Comment by lafama** [comment] 2017-09-26 12:12
Just realised that after a while no new messages are being pulled but no errors are logged.

**Comment by callmehiphop** [comment] 2017-09-26 16:47
Are you running your code in a specific environment (GKE?) and do you know after about how long do the messages stop coming?

**Comment by lafama** [comment] 2017-09-28 04:46
No am running the code on my comp (OS: darwin x64). Will update on the exact time later

**Comment by callmehiphop** [comment] 2017-10-02 14:56
@lafama we issued a release today that I believe will address this issue. However if you think I closed it prematurely, please feel free to re-open.

**Closed** 2017-10-02 14:56 UTC
Labels: api: pubsub, type: bug
