### ISSUE TITLE
value object of reqOpts object does not have hasOwnProperty method

### ISSUE THREAD

**Issue by gajus** [GoogleCloudPlatform/google-cloud-node#2070] opened 2017-03-09 18:08 UTC
v0.48.0 of google-cloud package is resulting in an error when attempting to upload a file.

The following code is enough to reproduce the issue.

```js
import createGcloud from 'google-cloud';

const credentials = JSON.parse(new Buffer(process.env.GOOGLE_CLOUD_CREDENTIALS, 'base64').toString());

const gcloud = createGcloud({
  credentials,
  projectId: argv.googleProjectId
});

const gcs = gcloud.storage();
const bucket = gcs.bucket(argv.googleStorageBucketName);

const posterFilePath = 'replace with a file path';

await bucket.upload(posterFilePath, {
  destination: 'posters/test.jpg',
  gzip: true,
  metadata: {
    contentLanguage: 'en',
    contentType: 'image/jpeg'
  },
  predefinedAcl: 'publicRead',
  resumable: false,
  validation: 'md5'
});

```

The error itself is misleading (see https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2069):

```
Error: Sorry, we cannot connect to Cloud Services without a project ID. You may specify one with an environment variable named "GCLOUD_PROJECT". See https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/authentication for a detailed guide on creating an authenticated connection.
    at Object.<anonymous> (/Users/gajus/Documents/dev/applaudience/movie-editor/node_modules/google-cloud/node_modules/@google-cloud/common/src/util.js:55:29)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/gajus/Documents/dev/applaudience/movie-editor/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/gajus/Documents/dev/applaudience/movie-editor/node_modules/google-cloud/node_modules/@google-cloud/common/src/service-object.js:32:12)

```

The real error originates [here](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/1939deaa32298b3cbe123686e5c52f480c1d7ee2/packages/common/src/util.js#L521):

```diff
  if (is.object(value) && is.fn(value.hasOwnProperty)) {
    for (var opt in value) {
+      if (value.hasOwnProperty(opt)) {
        value[opt] = replaceProjectIdToken(value[opt], projectId);
      }
    }
  }
```

The `value` Object does not have `hasOwnProperty` method.

The `reqOpts` object looks like this:

```
{ method: 'POST',
  qs:
   { uploadType: 'multipart',
     name: 'posters/poster-1000216-2017-beauty-and-the-beast.jpg',
     predefinedAcl: 'publicRead' },
  uri: 'https://www.googleapis.com/upload/storage/v1/b/applaudience/o',
  multipart:
   [ { 'Content-Type': 'application/json',
       body: '{"contentLanguage":"en","contentType":"image/jpeg","metadata":{"applaudience-movie-id":1000216,"movie-release-year":"2017","movie-title":"Beauty and the Beast"},"contentEncoding":"gzip"}' },
     { 'Content-Type': 'image/jpeg', body: [Object] } ],
  headers:
   { 'User-Agent': 'gcloud-node-storage/0.7.0',
     Authorization: 'Bearer REDACTED' } }
value { end:
   [ { [Function: bound onceWrapper] listener: [Function: onend] },
     [Function: onend] ],
  prefinish: { [Function: bound onceWrapper] listener: [Function] },
  finish: [Function: onfinish],
  error: { [Function: f] called: false },
  close: [Function: onclose],
  drain: [Function: ondrain] }
```

Not very useful, but confirms that the former code sample is creating the error.

For whatever reason (I didn't dig that deep), the object contained in the `value` property does not have `hasOwnProperty` method. In case relevant, Node.js v7.7.1.

**Comment by stephenplusplus** [comment] 2017-03-09 18:12
This is interesting, and the same issue as https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2050. We (tried to) fix that by adding `is.fn(value.hasOwnProperty)` before attempting to call `value.hasOwnProperty`. The fix is in master, and released under `@google-cloud/common@0.12.2`, but didn't make it into `google-cloud@0.48.0`. Can you try installing `@google-cloud/storage` and see if it was a satisfactory fix?

**Comment by gajus** [comment] 2017-03-09 18:19
Just installing `@google-cloud/common` will not do any good.

Something like this should work, though:

```bash
npm install @google-cloud/common
rm -fr ./node_modules/google-cloud/node_modules/@google-cloud/common
```

I can confirm that it fixes the problem.

Is there a workaround in the mean time that doesn't require deleting files?

**Comment by stephenplusplus** [comment] 2017-03-09 18:22
'google-cloud' is just a bundled package that includes all of the service APIs. So you can install just '@google-cloud/storage' and use it directly until the 'google-cloud' package is updated. Sorry you ran into this. I will try to put out a new release today.

**Closed by stephenplusplus** 2017-03-09 18:22 UTC

**Comment by abdulj** [comment] 2017-05-01 07:47
I am running in to this issue since yesterday.  The code is in cloud functions trying to access cloud storage using "@google-cloud/storage": "1.1.0" . 
const Storage = require('@google-cloud/storage')();


Error: Sorry, we cannot connect to Cloud Services without a project ID. You may specify one with an environment variable named "GCLOUD_PROJECT". See https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/authentication for a detailed guide on creating an authenticated connection.
    at Object.<anonymous> (/user_code/node_modules/@google-cloud/storage/node_modules/@google-cloud/common/src/util.js:55:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/node_modules/@google-cloud/storage/node_modules/@google-cloud/common/src/service-object.js:32:12)
    at Module._compile (module.js:570:32)"   


The same cloud function also connects to datastore, which works without hitting this issue.

**Comment by stephenplusplus** [comment] 2017-05-01 12:37
@abdulj are you running a specific method in the Storage API when you see the error?

**Comment by abdulj** [comment] 2017-05-01 12:42
@stephenplusplus   I tried the below written two ways , both leading to this error. 
1.
```
var file = bucket.file(name);
file.save(content,options, (err) => {
                //custom code here
        });

```
2. 

```
var file = bucket.file(name);
 str.pipe(file.createWriteStream(options))
                .on ('error',function(err) {
                       // custom code removed
                        } )
                .on('finish',function() {
                     // custom code removed
                        } );


```

**Comment by stephenplusplus** [comment] 2017-05-01 13:20
@abdulj I've been trying and failing to reproduce. Could you try this isolated example and see that it still occurs? https://gist.github.com/stephenplusplus/adf3b2bf3a6df17d3178def4a31aba6c

**Comment by abdulj** [comment] 2017-05-01 16:10
@stephenplusplus  thanks for the quick responses :)  and sorry that I did not debug enough before commenting here.  
    Looks like I was passing an object for filename instead of a string, this was entity key from datastore. I wanted the entity key (numeric ID) to be used as filename, and passed the key object as filename.   Error was misleading though.  Thanks again.

**Comment by stephenplusplus** [comment] 2017-05-01 18:29
I'm glad it worked out! We have an issue to address the confusing error here: #2069 -- sorry for that :(
