### ISSUE TITLE
dead links in docs

### ISSUE THREAD

**Issue by burnzzz** [GoogleCloudPlatform/google-cloud-node#2642] opened 2017-10-02 00:19 UTC
The link to the documentation for StreamingRecognitionConfig is dead/empty -> 

https://googlecloudplatform.github.io/google-cloud-node/#/docs/speech/0.10.0/#/index.json/data_types?method=StreamingRecognitionConfig

**Comment by stephenplusplus** [comment] 2017-10-10 21:52
Thanks for reporting. Closing as duplicate of #2546.

**Closed by stephenplusplus** 2017-10-10 21:52 UTC
Labels: docs, type: bug
