### ISSUE TITLE
datastore.update is not documented in the reference

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/google-cloud-node#2445] opened 2017-07-10 14:02 UTC
According to [this Datastore documentation page](https://cloud.google.com/datastore/docs/concepts/entities#updating_an_entity), `datastore.update(entity)` exists and can be used to update an entity. 

However, the reference of the node module is mot documenting this method: https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.56.0/datastore

**Comment by steren** [comment] 2017-07-10 14:04
Either the sample should be updated, or the method should be documented.

**Comment by steren** [comment] 2017-07-10 14:06
This is the sample in question: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/datastore/concepts.js#L323

**Comment by steren** [comment] 2017-07-12 08:28
@jmdobry

**Comment by callmehiphop** [comment] 2017-07-12 10:43
Thanks for reporting! This is a duplicate of #2431, which we're currently looking into!

**Closed by callmehiphop** 2017-07-12 10:43 UTC
