### ISSUE TITLE
Could not authenticate request

### ISSUE THREAD

**Issue by KKHAN1991** [GoogleCloudPlatform/google-cloud-node#2777] opened 2017-12-15 11:45 UTC
Hi,

I am trying to upload a file to my google cloud storage bucket, but i am receiving the error below.

> Error: Could not authenticate request
> ENOENT: no such file or directory, open '/var/www/project/server/{'
>     at wrapError (/var/www/project/server/node_modules/gcs-resumable-upload/index.js:24:10)
>     at /var/www/project/server/node_modules/gcs-resumable-upload/index.js:274:30
>     at getToken (/var/www/project/server/node_modules/google-auto-auth/index.js:24:9)
>     at getAuthClient (/var/www/project/server/node_modules/google-auto-auth/index.js:178:9)
>     at <anonymous>
> 

#### Environment details

  - OS: Ubuntu 16.04
  - Node.js version: v8.9.3
  - npm version: 5.5.1
  - google-cloud-node version:   @google-cloud/storage: "^1.5.1",

#### Steps to reproduce
```

let Config = require('../../config/app');
let Storage = require('@google-cloud/storage');

class GoogleCloudStorage {

    constructor() {

        this.bucketName = Config.filesystem.google.bucket;

        this.storage = new Storage({
            projectId: Config.filesystem.google.projectId,
            keyFilename: Config.filesystem.google.service_account_key,
        });
    }

    sendUploadToGCS(req, res, next) {

        if (!req.file) {
            return next();
        }

        console.log(req.file);

        const gcsname = Date.now() + req.file.originalname;
        const file = this.storage.bucket(this.bucketName).file(gcsname);
        console.log(file);

        const stream = file.createWriteStream({
            metadata: {
                contentType: req.file.mimetype,
            },
        });

        stream.on('error', (err) => {
            req.file.cloudStorageError = err;
            next(err);
        });

        stream.on('finish', () => {
            req.file.cloudStorageObject = gcsname;
            file.makePublic().then(() => {
                req.file.cloudStoragePublicUrl = getPublicUrl(gcsname);
                next();
            });
        });

        stream.end(req.file.buffer);
    }

    getPublicUrl(filename) {
        return 'https://storage.googleapis.com/' + this.bucketName + '/' + filename;
    }


}

```
```
module.exports = GoogleCloudStorage;

app.use('/upload', m.single('avatar'), storage.sendUploadToGCS.bind(storage), (req, res) => {
    console.log(req.file);
    return res.json('1');
});

```

**Comment by stephenplusplus** [comment] 2017-12-15 17:25
Duplicate of https://github.com/googleapis/nodejs-storage/issues/106.

**Closed by stephenplusplus** 2017-12-15 17:25 UTC
