### ISSUE TITLE
subscription.on message wasn't received of messagActually unrelated failures, but we should bump this anyway.es after 10 mins or more.

### ISSUE THREAD

**Issue by QTGate** [GoogleCloudPlatform/google-cloud-node#2598] opened 2017-09-07 17:42 UTC
- OS: Debian
  - Node.js version:  8.4.0
  - npm version:   5.4.0
  - google-cloud-node version:  0.56.0
  - @google-cloud/pubsub version: 0.14.0

#### Steps to reproduce

```js
const pubsub = require ( '@google-cloud/pubsub' )( connectOption )

const subscription = pubsub.topic ( topicName ).subscription ( subScription )

subscription.on ('message', message => {
    message.ack()
    ....
})

subscription.once('error', err => {
    ....
})
```

I received all un-received messages when I restart it.
I checked the connectionPool object when it have not received message:
connectionPool.isPaused [false]
connectionPool.isOpen [true]
connectionPool.connections [5]

Thank you.

**Comment by callmehiphop** [comment] 2017-09-08 18:19
Thanks for reporting! We've had multiple reports of similar behavior and we're currently investigating this issue. In the meantime you might want to use pubsub v0.13.x as a temporary workaround.

**Comment by QTGate** [comment] 2017-09-08 23:32
Thank you.
I did a temp code to use the pubsub v0.14.0 like this:
```js
const pubsub = require ( '@google-cloud/pubsub' )( connectOption )

const listenSub = () => {
    let subscription = pubsub.topic ( topicName ).subscription ( subScription )
    subscription.on ( 'message', message => {
        message.ack()
        ....
   })

    subscription.once('error', err => {
        ....
    })

    //        each 10 mins restart
    const tt = setTimeout (() => {
	subscription.close().then(() => {
		listenPubSubMaster = null
		return listenSub ()
    }, 600000 )
}
listenSub()
```

**Comment by caseyduquettesc** [comment] 2017-09-18 03:20
We see a similar behavior, although it takes a few hours. Eventually the subscription stops processing new messages and we have to restart the subscription. This only started after upgrading to 0.14.

**Comment by mscottx88** [comment] 2017-09-22 18:52
I too am seeing the same problem.  We set up a forever running process on GKE and it seems to go unresponsive after some time.  I came to the same conclusion of putting a restarter.  

Let's hope this gets resolved soon!

**Comment by callmehiphop** [comment] 2017-09-23 00:04
This is definitely a result of moving towards the new streaming API, I'm working on resolving this issue, but in the mean time I suggest downgrading to 0.13. I'll update this issue once it's been resolved.

**Comment by pongad** [comment] 2017-09-23 10:44
@callmehiphop FYI, we resolved this in Go by adding gRPC keepalive. I'm not sure how the code should look like in Node though. https://code-review.googlesource.com/#/c/gocloud/+/17070/

**Comment by callmehiphop** [comment] 2017-09-25 14:10
@pongad thanks for the update! I believe we just have to set the `grpc.keepalive_time_ms` option.

**Comment by callmehiphop** [comment] 2017-09-25 14:17
@QTGate @mscottx88 @caseyduquettesc I've opened a PR (#2627) which I believe will fix the issue you are seeing, would any of you mind testing it out? Thanks!

**Comment by mscottx88** [comment] 2017-09-25 14:18
I'm willing to give it a go, for sure!

**Comment by mscottx88** [comment] 2017-09-25 22:46
@callmehiphop I applied the two fixed files to my deployment but now I am seeing duplication of message delivery.  That is, I am seeing the same message being published more than one time.

**Comment by callmehiphop** [comment] 2017-09-26 17:30
@jganetsk I'm noticing that messages that are not acked before a stream is closed will be redelivered when the next stream is opened regardless of whether or not the ack deadline was hit. Is that the expected behavior? If so I'm assuming we need to filter these messages out.

**Comment by jganetsk** [comment] 2017-09-26 17:45
@callmehiphop I don't think you should be filtering any messages out. In general, it is possible to receive duplicates, and it is possible that they come before the ack deadline was hit. If this happens consistently, that's a problem that we should look at. How much time passes between delivery and redelivery? Does it correspond to the default ack deadline?

**Comment by jganetsk** [comment] 2017-09-26 18:05
We will take a look at this, thanks for reporting it.

**Comment by callmehiphop** [comment] 2017-09-26 18:07
@jganetsk as far as I can tell it only happens when closing and re-opening a stream. I'm putting together an elaborate test and I'll give you the details of my findings once I have some to share.

**Comment by callmehiphop** [comment] 2017-09-26 21:06
There appears to be 2 different scenarios in which messages will be redelivered before they have been acked.

### Streams being closed.

In the event of a stream being closed it appears that all un-acked messages will be redelivered to a different stream regardless of the current ack deadline.

  * **Test 1:** Set the initial `streamAckDeadlineSeconds` to 60 (1 minute) and close a stream after 30 seconds. <br>**Result:** All messages were redelivered despite not hitting the deadline.
  * **Test 2:** Modify the deadline just before closing the stream. <br>**Result:** All messages were redelivered even though the deadline was successfully modified.

### Race Condition

I believe we occasionally hit a race condition when attempting to modify an existing ack deadline. Currently we calculate the ack deadline using the 99th percentile of ack times (`p99`). We then calculate a delay to determine when we should modify the ack deadline (`Math.random() * n99 * 0.9`). 

If our `p99` value is 10, then it is possible we will not modify the ack deadline until roughly 1 second before it hits. The redelivery cases I have observed occurred when the delay was within 1-2 seconds of the `p99` value.

@lukesneeringer have you seen anything similar to what I'm describing above in the Python client? If this is indeed the reason why a redelivery occurs, is it reasonable to calculate the sleep time at a lower percent?

**Comment by mscottx88** [comment] 2017-09-30 00:22
Here is my solution to the race condition you describe.  A simple `activeMessages` tracking mechanism, combined with async shutdown that is event-driven.

`'use strict';

const config = require('@google-cloud/rcloadenv');
const cp = require('child_process');
const fs = require('fs-extra');
const logger = require('winston');
const pubsub = require('./providers/pubsub');
const uuid = require('uuid/v4');

const { name: configurationStorageName } = require('../package.json');

/**
 * Listen for and process incoming messages.
 *
 * @returns {Function}
 * An async function that can be called to stop listening for messages.
 */
const listen = () => {
  let activeMessages = 0;
  logger.info(`Subscription started at ${new Date().toISOString()}.`);

  const subscription = pubsub
    .get()
    .topic(process.env.SUBSCRIBE_TOPIC_NAME)
    .subscription(process.env.SUBSCRIBE_SUBSCRIPTION_NAME, {
      flowControl: {
        maxMessages: +process.env.MAX_CONCURRENT_MESSAGES
      }
    });

  subscription.on('error', (error) => {
    logger.error(error);
  });

  subscription.on('message', (message) => {
    const { email, pwd, uid } = message.attributes;
    logger.info(`Message received at ${new Date().toISOString()} for uuid ${uid}.`);

    const sessionId = uuid();
    const downloadPath = `${__dirname}/../downloads/${sessionId}`;
    const profilePath = `${__dirname}/../profiles/${sessionId}`;

    const args = [
      uid,
      email,
      pwd,
      sessionId,
      downloadPath,
      profilePath
    ];

    const options = {
      cwd: process.cwd(),
      env: process.env,
      execArgv: [],
      silent: true
    };

    logger.info(`Starting session ${sessionId}`);
    const downloader = cp.fork(`${__dirname}/download.js`, args, options);
    activeMessages++;

    downloader.stdout.on('data', (data) => {
      const text = new Buffer(data).toString('utf8');
      logger.info(text);
    });

    downloader.on('exit', async (code) => {
      logger.info(`Session ${sessionId} completed with exit code ${code}.`);

      try {
        await Promise.all([fs.remove(downloadPath), fs.remove(profilePath)]);
      } catch (error) {
        logger.error(`Could not cleanup path(s) in session ${sessionId} because of ${error}.`);
      }

      try {
        message.ack();
      } finally {
        activeMessages--;
      }
      if (activeMessages === 0) {
        subscription.emit('importer-idle');
      }
    });
  });

  return () => {
    return new Promise((resolve, reject) => {
      // stop the flow of incoming messages
      subscription.removeAllListeners('message');

      const shutdown = async () => {
        try {
          await subscription.close();
          logger.info(`Subscription ended at ${new Date().toISOString()}.`);
          resolve();
        } catch (error) {
          reject(error);
        }
      };

      if (activeMessages !== 0) {
        subscription.on('importer-idle', shutdown);
      } else {
        shutdown();
      }
    });
  };
};

/**
 * Run the process.
 *
 * @returns {void}
 */
const run = async () => {
  logger.level = process.env.LOG_LEVEL;

  try {
    await config.getAndApply(configurationStorageName);
  } catch (error) {
    logger.error(error);
    throw error;
  }

  let unlisten = listen();

  setInterval(async () => {
    try {
      await unlisten();
    } catch (error) {
      logger.error(error);
    } finally {
      unlisten = listen();
    }
  }, +process.env.RESTART_INTERVAL);
};

module.exports = {
  run
};
`

**Comment by QTGate** [comment] 2017-10-16 01:04
- OS: Debian
  - Node.js version:  8.7.0
  - npm version:   5.5.1
  - @google-cloud/pubsub version: 0.14.5

#### Steps to reproduce

```js
const pubsub = require ( '@google-cloud/pubsub' )( connectOption )

const listenSub = () => {
    let subscription = pubsub.topic ( topicName ).subscription ( subScription )
    subscription.on ( 'message', message => {
        message.ack()
        ....
   })

    //        each 10 mins restart
    const tt = setTimeout (() => {
	return subscription.close().then(() => {
	    listenPubSubMaster = null
	    return listenSub ()
    }, 600000 )
}

listenSub()
```
I did make new subscription each 10 mins.
But looks the @google-cloud/pubsub not release memory when pubsub exit with subscription.close().

[
![pubsub](https://user-images.githubusercontent.com/19976150/31591286-ee33b5ec-b1d2-11e7-8c25-cef6eb390901.jpeg)
](url)

**Comment by ShahNewazKhan** [comment] 2017-10-18 19:23
-     OS: Debian
-     Node.js version: 6.11.1
-     npm version: 3.10.10
-     version: 0.14.5

I am also seeing the memory increase and not being released after implementing the subscriber refresh.

**Comment by stephenplusplus** [comment] 2017-11-03 07:43
@callmehiphop will this be addressed by #2716 or another issue/PR you've already worked on?

**Comment by QTGate** [comment] 2017-11-03 08:00
No I am not. Even the new v0.14.6. Also have memory problem. I plan do subscription.on gCloud API's by my self.

**Comment by callmehiphop** [comment] 2017-11-03 18:46
> @callmehiphop will this be addressed by #2716 or another issue/PR you've already worked on?

I believe it will!

**Comment by ChrisBartonLC** [comment] 2017-11-05 23:12
I am using PubSub node.js client version 0.14.5 and I sometimes have CloudFunctions that when triggered are no longer able to add messages to a topic or pull messages from a subscription. The fix is to redeploy the CloudFunction which mostly works but not always. The issue is intermittent.

**Comment by rhodgkins** [comment] 2017-11-09 10:51
Apologies for asking the obvious...!

But is this now fixed as #2716 has been released with 0.14.8?

Cheers!

**Comment by callmehiphop** [comment] 2017-11-09 19:06
@rhodgkins which parts? I think there are a number of issues being described here.

**Comment by rhodgkins** [comment] 2017-11-13 18:38
@callmehiphop the issue around no messages being received on a subscription after a period of time.

**Comment by callmehiphop** [comment] 2017-11-13 18:48
@rhodgkins from what I understand the only environment in which this occurs is GKE, but I also know a fix was deployed on the GKE side of things that should have resolved it. I haven't seen or heard of any reports verifying this though.

**Comment by stephenplusplus** [comment] 2017-12-13 03:38
This issue was moved to googleapis/nodejs-pubsub#10

**Closed by stephenplusplus** 2017-12-13 03:38 UTC
Labels: api: pubsub, status: blocked

**Comment by mchavarriae** [comment] 2017-12-29 21:11
Recently we start experimenting the problem using version 0.13.0, Does anybody has this problem?
