### ISSUE TITLE
Module instancing problem with storage+bigquery.import

### ISSUE THREAD

**Issue by jakeorr** [GoogleCloudPlatform/google-cloud-node#1516] opened 2016-08-22 18:44 UTC
Hi,

I am trying to switch to the new method of requiring only the modules that I need instead of the entire google-cloud module. I'm running into a problem importing files from cloud storage into bigquery. This was working until I switched to requiring separate modules.

```javascript
const bigQuery = require('@google-cloud/bigquery')({
  projectId: [projectId],
  client_email: [email],
  private_key: [key string]
});

const gcs = require('@google-cloud/storage')({
  projectId: [projectId],
  client_email: [email],
  private_key: [key string]
});

var file = gcs.bucket([bucket name]).file('afile.csv');

// This debug output prints "true"
console.log(file instanceof require("@google-cloud/storage").File);

bigQuery
  .dataset([dataset ID])
  .table([table ID])
  .import([file], next);
```

The import call fails with:
```
Error: Source must be a File object.
    at /[project dir]/node_modules/@google-cloud/bigquery/src/table.js:809:15
```

Adding a debug prop to `require('@google-cloud/storage')`, it looks like my app and the bigquery modules have two different instances of the storage module, causing instanceof to report the files passed as being the wrong type.

#### Environment details

  - OS: OSX 10.11.6
  - Node.js version: v4.4.4
  - npm version: 2.15.1
  - gcloud-node version: v0.1.1 for both /bigquery and /storage

This seems like a bug, but I could be missing something. Any help would be appreciated, thanks!

**Comment by stephenplusplus** [comment] 2016-08-22 23:35
:\ Sorry about that. This is because of the way we type check for custom types. We have [an issue](#1467) that is suggesting a better way to do that, which would fix this at the same time. I'm going to assign that one to myself and start on it tomorrow so that hopefully we can release a fix shortly.

Closing only because #1467 will track the fix.

**Closed by stephenplusplus** 2016-08-22 23:35 UTC
Labels: bigquery

**Comment by jakeorr** [comment] 2016-08-22 23:42
Excellent, thanks Stephen! For now I'm just using the entire google-cloud package so things are still working 👍

**Comment by stephenplusplus** [comment] 2016-08-22 23:46
Phew 😌 Thanks for being patient with the bumps from the modularization releases!

**Comment by erdillon** [comment] 2017-09-19 16:34
Hi there. I'm running into the same issue. Is that no fixed?

**Comment by stephenplusplus** [comment] 2017-09-21 14:40
@erdillon can you open a new issue, including steps to reproduce and environment information?
