### ISSUE TITLE
unHandled rejection while using pubsub when server is overloaded

### ISSUE THREAD

**Issue by akshendra** [GoogleCloudPlatform/google-cloud-node#1941] opened 2017-01-29 16:01 UTC
I am using [google-cloud-node](https://github.com/GoogleCloudPlatform/google-cloud-node)'s PubSub module which is using grpc. It starts off well but after some time I see errors like below.

```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: A pull requests for subscription '/subscriptions/<project>/<subscription>' went to a server that is temporarily overloaded. Please try the request again.
at /<dir>/node_modules/grpc/src/node/src/client.js:417:17
```

I have an event handler on the subscription for errors, but it seems the error does not propagate to it

**Comment by stephenplusplus** [comment] 2017-02-16 17:44
@akshendra do you have some code that can reproduce?

**Comment by akshendra** [comment] 2017-02-17 08:45
This is the code I am using,
```
const subscription = topic.subscription(subName, options);
const result = yield subscription.create();
result[0].on('message', cb);
result[0].on('error', console.error);
```

**Comment by stephenplusplus** [comment] 2017-02-17 17:25
@callmehiphop can you think of a way this could happen?

**Comment by stephenplusplus** [comment] 2017-02-17 17:26
Linking since it's related to the error itself: https://groups.google.com/forum/#!topic/cloud-pubsub-discuss/dGOXiL118Sw

The mystery is still how the error was not caught.

**Comment by callmehiphop** [comment] 2017-02-17 17:43
@akshendra @stephenplusplus I'm guessing the error is coming from `subscription.create()` since there doesn't appear to be any error handling around the creation of the subscription. I think you would need to wrap that block in a try/catch to look like

```js
const subscription = topic.subscription(subName, options);

try {
  const result = yield subscription.create();
  result[0].on('message', cb);
  result[0].on('error', console.error);
} catch (e) {
  console.error(e);
}
```

**Comment by stephenplusplus** [comment] 2017-02-17 17:45
So the `Error:` line itself is from the `result[0].on('error') handler`?

**Comment by callmehiphop** [comment] 2017-02-17 17:55
Actually I'm not sure, I initially thought it was from the `create()` call but that's clearly a pull error.

**Comment by stephenplusplus** [comment] 2017-02-21 19:23
@akshendra have you seen this error since the error itself (`A pull requests for subscription '/subscriptions/<project>/<subscription>' went to a server that is temporarily overloaded. Please try the request again.`) was resolved?

**Comment by akshendra** [comment] 2017-02-22 05:45
@stephenplusplus Yeah the error was resolved and I did not get this after that.

**Comment by stephenplusplus** [comment] 2017-02-22 14:51
Alright, I think I'll close this issue since we can't seem to reproduce the underlying unhandled rejection error. If something like this happens again, we'll re-investigate. Thanks for reporting, and I'm sorry you had this little hiccup, but thankfully everything is up and running well again.

**Closed by stephenplusplus** 2017-02-22 14:51 UTC
Labels: API: pubsub, Type: Bug
