### ISSUE TITLE
Extension Headers construction in storage file.getSignedUrl doesn't follow spec

### ISSUE THREAD

**Issue by moomou** [GoogleCloudPlatform/google-cloud-node#1818] opened 2016-11-23 23:50 UTC
According to [docs](https://cloud.google.com/storage/docs/access-control/signed-urls#about-canonical-extension-headers) here, there are multiple things required to get a proper signed url with extension headers. 

However, reading the source code, it looks like docs' requirements are not [followed](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/storage/src/file.js#L1474-L1483).

I tried generating signed urls with the nodejs `file.getSignedUrl` with no luck but everything works if I take out the extension headers.

**Comment by stephenplusplus** [comment] 2016-11-24 00:03
Can you show code that works and then the code that does? It looks like there are rules to follow for handling extension headers, but if you were to follow those rules on your side with the `config.extensionHeaders` argument, it seems like we'd properly pass it through correctly.

I do think we should follow those rules on our side (PR welcome!), but I just want to be sure that we're not missing anything else, provided the user has given us a properly-formed object.

Thanks for opening this!

**Comment by moomou** [comment] 2016-12-01 02:10
```const gcloud = require('google-cloud');
const Promise = require('bluebird');

const gcs = gcloud.storage({
  projectId: 'grape-spaceship-123',
  keyFilename: '/path/to/keyfile.json'
});

const bucket = gcs.bucket('bucket');
const file = Promise.promisify(bucket.file('/dummy/123'));

function getUrl(extensionHeaders=null) {
  return file.getSignedUrlAsync({
    extensionHeaders,
    action: 'write',
    expires: now.setMinutes(now.getMinutes() + 10),
    contentType: 'application/octet-stream',
  });
}

getUrl().then(url => {
  console.log('signed url with extension headers::', urlWithExtensionHeader);
});

getUrl({
  'x-goog-custom-id': 'customer123',
}).then(url => {
  console.log('signed url without extension headers::', url);
});
```

Then I would do a `POST` from a separate program but always get 403 for the url with extension header.

Also, preprocessing does not help in this case as object iteration order is not guaranteed in js.

**Comment by stephenplusplus** [comment] 2017-02-16 19:16
Sorry that this has sat for so long. I've tried to reproduce using the following script and the latest @google-cloud/storage. This works successfully for me, and fails if I don't include the `x-goog-custom-id` to `request.put`.

Also note that `getSignedUrl` uses `PUT` (not `POST`) for `write` actions, per the docs here:

> Note: The HTTP verb POST is not supported in signed URL strings, except as noted above. You can use POST to define signed policy documents, which specify the characteristics of objects that can be uploaded to a bucket. Learn more in the POST Object documentation.
> \- https://cloud.google.com/storage/docs/access-control/signed-urls

```js
'use strict'

const gcs = require('@google-cloud/storage')({
  keyFilename: 'C:/users/sawch/dev/key.json'
})
const request = require('request')

const bucket = gcs.bucket('stephen-has-a-new-bucket')
const file = bucket.file('file-name')

file.getSignedUrl({
  action: 'write',
  expires: '3-17-2017',
  extensionHeaders: {
    'x-goog-custom-id': 'customer123'
  }
}, (err, url) => {
  if (err) throw err

  var data = new Date().toString()

  request
    .put(url, {
      headers: {
        'x-goog-custom-id': 'customer123'
      }
    })
    .on('error', console.log)
    .on('complete', () => {
      file.download((err, contents) => {
        if (err) throw err
        if (contents.toString() !== data) throw new Error('Data mismatch')
        console.log('data matched!')
      })
    })
    .end(data)
})
```

**Comment by bjwatson** [comment] 2017-03-02 00:34
@moomou I'm closing this since it looks like @stephenplusplus answered your question. Please reopen if you're still having this problem.

**Closed by bjwatson** 2017-03-02 00:34 UTC
Labels: API: storage, help wanted, Priority: P2+, Status: Acknowledged, Type: Question
