### ISSUE TITLE
"The request signature we calculated does not match the signature you provided."

### ISSUE THREAD

**Issue by kirankumar-mahi** [GoogleCloudPlatform/google-cloud-node#2439] opened 2017-07-06 17:17 UTC
Hi,

I am using latest aws-java-sdk-s3', version: '1.11.158'. I am getting SignatureDoesNotMatch error. I am using below code.

**The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method. com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: null**

 ClientConfiguration clientConfiguration = new ClientConfiguration();
AWSCredentials awsCredentials = new BasicAWSCredentials("XXX","XXX");
AmazonS3 amazonS3Client = AmazonS3ClientBuilder.standard().withCredentials(new AWSStaticCredentialsProvider(awsCredentials)).withClientConfiguration(clientConfiguration)
                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("https://storage.googleapis.com","Multi-Regional")).build();

            String keyName = UUID.randomUUID().toString();
            FileInputStream f = new FileInputStream(new File(filePath));
            TransferManager tx =  TransferManagerBuilder.standard().withS3Client(amazonS3Client).build();

            // Request server-side encryption.
            ObjectMetadata objectMetadata = new ObjectMetadata();
            objectMetadata.setSSEAlgorithm(ObjectMetadata.AES_256_SERVER_SIDE_ENCRYPTION);
            objectMetadata.setContentType("application/octet-stream");

            tx.upload("XX", keyName, f,objectMetadata);

**Comment by stephenplusplus** [comment] 2017-07-06 19:38
Can you walk me through how I can reproduce this?

**Comment by kirankumar-mahi** [comment] 2017-07-07 05:03
Hi Stephen,

I am attaching the sample gradle project. Please unzip and run the project with your access,  secret key and file. 

[aws-sdk-test.zip](https://github.com/GoogleCloudPlatform/google-cloud-node/files/1130037/aws-sdk-test.zip)

**Comment by stephenplusplus** [comment] 2017-07-08 18:06
Is there a way to reproduce this error outside of the AWS environment?

**Comment by kirankumar-mahi** [comment] 2017-07-08 18:19
I am storing the files in the  google cloud s3 bucket (Google cloud S3 environment) using aws sdk S3. As google lets Cloud Storage interoperate with tools written for other cloud storage systems like aws sdk. I am using latest aws sdk s3.

**Comment by stephenplusplus** [comment] 2017-07-08 18:38
@lukesneeringer is it clear to you how we should debug this issue?

**Comment by kirankumar-mahi** [comment] 2017-07-10 13:49
@lukesneeringer - if you require more information, please let me know.
Is there any thing that I need to check at signature version. In my code- i commented out signature version code . I tried various possibilities and could not get through.

**Comment by lukesneeringer** [comment] 2017-07-10 15:07
Hi @kirankumar-mahi,
Thanks for reporting.

This repository is for the Node.js client libraries, which I am fairly certain is not what you are after, since as best as I can tell, you are writing Java code. I would recommend opening an issue on [google-cloud-java][].

Sorry...I know it is frustrating to be redirected, but none of the folks who maintain this repo are going to know how to help you. :-(

I am going to close this, but if I goofed somehow, please feel free to re-open.

  [google-cloud-java]: https://github.com/GoogleCloudPlatform/google-cloud-java

**Closed by lukesneeringer** 2017-07-10 15:07 UTC
