### ISSUE TITLE
datastore query.runStream: this.end() crashes

### ISSUE THREAD

**Issue by igorclark** [GoogleCloudPlatform/google-cloud-node#1966] opened 2017-02-06 14:01 UTC
Hi there, I'm using `@google-cloud/datastore@0.7.0`, and trying to use `query.runStream()`.

When I call `this.end()` it crashes with `this.end is not a function `:

```js
var datastore = require('@google-cloud/datastore')({
  projectId: '<my-project-id>'
});

let query = datastore.createQuery( '<my-entity-type>' );

let results = [];

query.runStream()

    .on(
        'error',
        console.error
    )

    .on(
        'data',
        ( entity ) => {
            this.end(); // <- HERE BE CRASH
        }
    )

    .on(
        'info',
        ( info ) => {}
    )

    .on(
        'end',
        () => {
            console.log( results.length );
        }
    );

```
At first I thought it might be because the `this` is not accessible inside a Promise, or something to do with `babel`  translation. So I made the simplest possible test case using only basic ES5 as above, and it still crashes when running directly in `node` as a separate standalone script:

```
$ node test.js
[ ... ]/src/test.js:41
                this.end();
                     ^

TypeError: this.end is not a function
    at DestroyableTransform.query.runStream.on.on ([ ... ]/src/test.js:41:22)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:188:7)
    at readableAddChunk ([ ... ]/node_modules/readable-stream/lib/_stream_readable.js:217:18)
    at DestroyableTransform.Readable.push ([ ... ]/node_modules/readable-stream/lib/_stream_readable.js:176:10)
    at DestroyableTransform.Transform.push ([ ... ]/node_modules/readable-stream/lib/_stream_transform.js:123:32)
    at [ ... ]/node_modules/split-array-stream/index.js:15:14
    at Object.async.whilst ([ ... ]/node_modules/split-array-stream/node_modules/async/lib/async.js:792:13)
    at module.exports ([ ... ]/node_modules/split-array-stream/index.js:9:9)
    at onResultSet ([ ... ]/node_modules/@google-cloud/datastore/src/request.js:671:5)
```

Does this seem like a bug? Or am I doing something wrong? Hope it's just me, as I really need to be able to terminate query streams as early as possible.

Cheers,
Igor

**Comment by stephenplusplus** [comment] 2017-02-06 18:52
I've been able to reproduce this issue. I'm not sure what the cause is yet, however as a temporary solution, you can use this in your app:

```diff
let query = datastore.createQuery( '<my-entity-type>' );

let results = [];

- query.runStream()
+ let stream = query.runStream()

+ stream
    .on(
        'error',
        console.error
    )

    .on(
        'data',
        ( entity ) => {
-            this.end(); // <- HERE BE CRASH
+           stream.end();
        }
    )

    .on(
        'info',
        ( info ) => {}
    )

    .on(
        'end',
        () => {
            console.log( results.length );
        }
    );
```

**Comment by igorclark** [comment] 2017-02-07 08:19
Thank you @stephenplusplus, that's a great workaround, and it reads a lot more clearly to me than `this` anyway.

Appreciate the swift & helpful response 👍

**Comment by danoscarmike** [comment] 2017-02-27 22:46
@igorclark @stephenplusplus closing this one.  Please reopen if you think this is premature!

**Comment by stephenplusplus** [comment] 2017-02-27 22:53
We do need to fix this on our end. It affects all streams, and our documentation where readable streams are returned is incorrect.

**Comment by igorclark** [comment] 2017-02-27 23:09
Hey guys - I just had a possible brainwave on this. I was back at the [node.js Event doc](https://nodejs.org/api/events.html) yesterday and noticed this little gem, but didn't relate it back to this issue until I saw the update notification just now:

> The `eventEmitter.emit()` method allows an arbitrary set of arguments to be passed to the listener functions. It is important to keep in mind that when an ordinary listener function is called by the `EventEmitter`, the standard `this` keyword is intentionally set to reference the EventEmitter to which the listener is attached.
>
>```
>const myEmitter = new MyEmitter();
>myEmitter.on('event', function(a, b) {
>  console.log(a, b, this);
>  // Prints:
>  //   a b MyEmitter {
>  //     domain: null,
>  //     _events: { event: [Function] },
>  //     _eventsCount: 1,
>  //     _maxListeners: undefined }
>});
>myEmitter.emit('event', 'a', 'b');
>```
>It is possible to use ES6 Arrow Functions as listeners, however, when doing so, the `this` keyword will no longer reference the EventEmitter instance:
>
>```const myEmitter = new MyEmitter();
>myEmitter.on('event', (a, b) => {
>  console.log(a, b, this);
>  // Prints: a b {}
>});
>myEmitter.emit('event', 'a', 'b');
>```

If it's just that, would a documentation update be enough?

If it's not, of course, move along now, nothing to see here 😉

**Comment by jmuk** [comment] 2017-02-28 00:35
Your code snippet uses the arrow functions, which does not bind `this`, so the `this` will refer to the object outside of the context. It's most likely to be the global context, not the stream.

**Comment by igorclark** [comment] 2017-02-28 10:09
@jmuk that's what I was thinking! In which case, just mentioning it in the documentation would be plenty, as the client code is doing what it's expected to do, right?

**Comment by jmuk** [comment] 2017-02-28 18:36
I don't think we need to update our document to mention this specifically -- this is more like a coding quiz of JavaScript language itself, and the mention in the NodeJS's document itself (which you linked) seems sufficient to me.

**Comment by igorclark** [comment] 2017-03-01 10:14
HI @jmuk, sure, makes sense. I was just thinking that if it was a subtle enough issue that @stephenplusplus and I didn't realise what was happening at first, it might be helpful to just mention it at the [runQueryStream](https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.47.0/datastore?method=runQueryStream) doc point, particularly as more and more people will likely want to use ES6 as time goes on. But I can see the argument either way.

**Comment by stephenplusplus** [comment] 2017-03-06 17:50
Unfortunately, the size of the change to mention this would be huge. I think because of this, let's leave it and revisit this if others stumble over the trickiness.

**Closed by stephenplusplus** 2017-03-06 17:50 UTC
Labels: API: datastore, Priority: P2+, Status: Acknowledged, Status: Won't Fix, Type: Question
