### ISSUE TITLE
Write more integration tests for BigQuery

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-node#2002] opened 2017-02-16 09:53 UTC
Please see email I sent about the details and test cases from @tswast . 

Also, C# has [some examples](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.IntegrationTests/ExhaustiveTypesTest.cs) that might be worth looking at.

/cc @jskeet @jba @tswast @danoscarmike

**Comment by stephenplusplus** [comment] 2017-02-16 16:44
Dupe of #2000 :)

**Closed by stephenplusplus** 2017-02-16 16:44 UTC
Labels: bigquery
