### ISSUE TITLE
Publish callback never called - Pubsub

### ISSUE THREAD

**Issue by askmon** [GoogleCloudPlatform/google-cloud-node#1940] opened 2017-01-27 15:46 UTC
#### Environment details

  - OS: Ubuntu 14.04
  - Node.js version: 4.5.0
  - npm version: 2.15.9
  - google-cloud-node version: 0.7.1

#### Steps to reproduce

  1. Publish many messages to pubsub

#### Expected behavior

All publish operations should call the callback function

#### Current behavior

Some publish operations hang, never calling the callback, or calling it after more than 5 minutes. When the callback is not called, the message is not delivered.

#### More descriptions

I'd like a way to set my own timeout on publish operations. As it's not clear how much time it will  keep trying to deliver it and the callback is not called, I can't create my own timeout to try sending again

The application was working normally for a week until the day before yesterday, then it started behaving like this.

Thanks!

**Comment by pyhrus** [comment] 2017-01-30 13:20
We are facing the same issue, the callback never gets called. Same behavior is also observed version 0.5.1

**Comment by paynen0** [comment] 2017-01-30 20:27
Are you using a push or pull type delivery flow?

[1] https://cloud.google.com/pubsub/docs/subscriber#push_pull

**Comment by paynen0** [comment] 2017-01-30 20:28
And what are the approximate stats on the subscriber? In terms of latency of processing, rate of fetching, etc.

**Comment by pyhrus** [comment] 2017-01-30 21:56
We are using pull workflow. Publish and subscriber rate is about 400 m/s

**Comment by kinok** [comment] 2017-02-01 13:22
Hey guys, 
We had the same issue using last version of `@google-cloud/pubsub@0.8.0`.
Downgrading the package to `0.7.0` allows us to make it work.

This may helps, here's a strace of a stucked process :
```
epoll_ctl(5, EPOLL_CTL_DEL, 12, 0x7ffe341de950) = 0
close(12)                               = 0
clock_gettime(CLOCK_MONOTONIC, {1934, 909990628}) = 0
clock_gettime(CLOCK_MONOTONIC, {1934, 910016041}) = 0
epoll_wait(5, [], 1024, 0)              = 0
clock_gettime(CLOCK_REALTIME, {1485955188, 856136057}) = 0
clock_gettime(CLOCK_REALTIME, {1485955188, 856164846}) = 0
clock_gettime(CLOCK_MONOTONIC, {1934, 910135906}) = 0
socket(PF_INET, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 12
connect(12, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("216.58.208.234")}, 16) = -1 EINPROGRESS (Operation now in progress)
clock_gettime(CLOCK_MONOTONIC, {1934, 910278190}) = 0
clock_gettime(CLOCK_MONOTONIC, {1934, 910297462}) = 0
clock_gettime(CLOCK_MONOTONIC, {1934, 910311290}) = 0
epoll_ctl(5, EPOLL_CTL_ADD, 12, {EPOLLOUT, {u32=12, u64=12}}) = 0
epoll_wait(5, 
```
This will repeat for a long time (indefinitely?)

**Comment by cades** [comment] 2017-02-02 09:02
facing the same issue +1
however, it works on my Macbook Air, but doesn't work when deployed to Google App Engine.

**Comment by cades** [comment] 2017-02-02 09:30
One difference between GAE and other environment is GAE run apps **in Docker**, does anyone willing help test it in a docker container?

**Comment by kinok** [comment] 2017-02-02 09:37
@cades the sample of the strace i gave above comes from a docker container (which runs on my laptop)

**Comment by cades** [comment] 2017-02-02 09:51
@kinok thanks! Hi @askmon and @pyhrus, does your app runs in a docker container, too?

**Comment by askmon** [comment] 2017-02-02 11:16
@cades I have seen it happen both on Docker containers and on GCE instances using Ubuntu, although it seems to happen more frequently on Docker containers

**Comment by stephenplusplus** [comment] 2017-02-02 18:55
Please try upgrading to the latest version of `google-cloud` or `@google-cloud/pubsub`.

**Comment by cades** [comment] 2017-02-03 03:29
hi @stephenplusplus, I tried 0.8.0, still not working.

**Comment by pyhrus** [comment] 2017-02-03 13:27
@cades No, we are run it in google compute engine instance.

@stephenplusplus, I see that new version for every gcloud sub package (`@google-cloud/bigquery`, `@google-cloud/datastore`, etc) was release yesterday with updated `commons-grpc` and `grpc` module, except for `@google-cloud/pubsub`, this is done intentionally ?

**Comment by weishyun** [comment] 2017-02-03 21:13
I am facing the exactly same issue. It works well when testing in local machine, but doesn't work when deploy to GAE since yesterday. If I revert the deployment to older version, the pub sub still working well. It has no code change in pubsub functionality, but the callback is never called.

**Comment by edmund-lee** [comment] 2017-02-04 01:43
I have tested the appengine pubsub sample code linked in the tutorial below. It does not work when deployed to Google App Engine but it works when run locally.
https://cloud.google.com/appengine/docs/flexible/nodejs/writing-and-responding-to-pub-sub-messages

**Comment by stephenplusplus** [comment] 2017-02-04 17:16
This is likely a duplicate of #1946. Please follow along there. Thank you and sorry for the trouble.

**Closed by stephenplusplus** 2017-02-04 17:16 UTC
Labels: bug, pubsub

**Comment by tonila** [comment] 2017-02-21 04:25
Hi, this is still happening in [node:6-alpine](https://hub.docker.com/_/node/).
