### ISSUE TITLE
Allow providing a service account directly for storage object

### ISSUE THREAD

**Issue by AyoubElk** [GoogleCloudPlatform/google-cloud-node#2549] opened 2017-08-21 21:57 UTC
In short, for a specific use case for a project, I'm handling multiple firebase accounts and the current setup stores the service accounts in a database instead of using the file system.

I need to be able to supply the service account directly to the storage constructor instead of specifying the file name as suggested in the docs:

     var gcs = storage({
       projectId: 'grape-spaceship-123',
       keyFilename: '/path/to/keyfile.json'
     });

**Comment by stephenplusplus** [comment] 2017-08-21 22:18
Duplicate of #2536

You can use the `options.credentials` object when instantiating the client. That is expected to be the contents of a JSON service account key file.

**Closed by stephenplusplus** 2017-08-21 22:18 UTC
