### ISSUE TITLE
Broken link in cloud spanner documentation

### ISSUE THREAD

**Issue by vkedia** [GoogleCloudPlatform/google-cloud-node#2653] opened 2017-10-04 22:28 UTC
If I go to v1 page under spanner documentation:
https://googlecloudplatform.github.io/google-cloud-node/#/docs/spanner/0.5.0/v1

The link to "Data Types" is broken:
https://googlecloudplatform.github.io/google-cloud-node/#/docs/spanner/0.5.0/spanner%2Fv1%2Fdata_types

This link takes me to not found.

**Comment by stephenplusplus** [comment] 2017-10-10 21:45
Closing as a duplicate of #2546.

**Closed by stephenplusplus** 2017-10-10 21:45 UTC
Labels: api: bigquery, docs, type: bug
