### ISSUE TITLE
Auth trouble in Google Cloud Functions

### ISSUE THREAD

**Issue by lukesneeringer** [GoogleCloudPlatform/google-cloud-node#2560] opened 2017-08-25 17:26 UTC
This is a re-post of an internal bug. (Googlers: b/62449180)

--------------------

Several customers have reported problems initializing Datastore and other clients within Google Cloud Functions. Interestingly, the `require` statements fail in global scope but succeed if they are within the function.

**Comment by lukesneeringer** [comment] 2017-08-25 17:28
Reproduction case. Note that if the requires are moved inside `handleGET`, the problem goes away.

```es6
/**
 * Responds to the GET method. If a recordId is defined, will return information about that specific record;
 * otherwise, will return all records of that Kind
 * 
 * @param {Object} req Cloud Function request context.
 * @param {Object} res Cloud Function response context.
 * @param {string} installationId Installation to get the record from
 * @param {string} kind Kind of record to get
 * @param {string} recordId which record to get
 */
const Datastore = require('@google-cloud/datastore');
const datastore = Datastore({
        projectId: projectId
});

function handleGET (req, res, installationId, kind, recordId) {
        var queries = [];
        var recordIds;
        var resultsArr = [];
        if (typeof recordId !== 'undefined' && recordId !== null) {
                queries[0] = datastore.createQuery(installationId,kind).filter('recordId', '=', recordId);
        } else {
                if (req.query.recordIds) {
                        recordIds = req.query.recordIds.split(',');
                        recordIds.map( (localRecordId, index) => {
                                queries[index] = datastore.createQuery(installationId,kind).filter('recordId', '=', localRecordId);
                        });
                } else {
                        queries[0] = datastore.createQuery(installationId,kind);
                }
        }
        for (var i = 0; i < queries.length; i++) {
                for (var property in req.query) {
                        if (property !== 'recordIds' && property !== 'querySort') {
                                queries[i] = queries[i].filter(property, '=', req.query[property]);
                        }
                }
        }
        /*NOTE: After reviewing the documentation, I do not believe there would be substantial gain by wrapping these in a transaction.
        Conversely, individual transactions contain a limit on the number of operations that, while reasonably high, is still potentially problematic.
        Consequently, I have decided not to wrap these in a transaction and to only do loose queries. This does mean there is a small possibility that
        the results of a query may represent different snapshots in time; however, I do not expect any real issues to result from this. In the
        event that this does become problematic, it is a simple matter of wrapping this in a transaction and redeploying.*/
        Promise.all(
                queries.map((query) => {
                        return datastore.runQuery(query)
                        .then((results) => {
                                if (results[0] && results[0].length > 0){
                                        for (var j = 0; j < results[0].length; j++) {
                                                resultsArr.push(results[0][j]);
                                        }       
                                }
                        })
                        .catch((err) => {
                                console.log('Error in query: ', err);
                                res.status(400).send(err);
                        });
                })
        )
        .then(() => {
        // Found entities of that kind
                if (resultsArr && resultsArr.length > 0) {
                        if (req.query && req.query.querySort) {
                                resultsArr = sortByProperty(resultsArr, req.query.querySort);
                        } 
                        res.status(200).send(resultsArr);
                } else {
                        if (recordId) {
                                res.status(200).send('No record with the Record ID ' + recordId + ' was found.');
                        } else {
                                res.status(200).send('Records of kind ' + kind + ' matching those criteria not found.');
                        }
                }
        })
                .catch((err) => {
                        res.status(400).send(err);
                });
}
```

**Comment by lukesneeringer** [comment] 2017-09-19 18:56
@stephenplusplus Can you look at this and figure out if it is related to the Node client libraries?

**Comment by stephenplusplus** [comment] 2017-11-02 20:41
This is a duplicate of https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2438#issuecomment-320952103.

**Closed by stephenplusplus** 2017-11-02 20:41 UTC
Labels: auth, priority: p2+, type: bug
