### ISSUE TITLE
npm ERR! registry error parsing json when installing via npm

### ISSUE THREAD

**Issue by ohad-bpal** [GoogleCloudPlatform/google-cloud-node#1980] opened 2017-02-10 15:42 UTC
Running
`npm install --save @google-cloud/storage`

Causes
`npm ERR! registry error parsing json`

node version 7.5.0
npm version 4.2.0

**Comment by stephenplusplus** [comment] 2017-02-10 15:49
Which package, OS, node & npm version?

**Comment by ohad-bpal** [comment] 2017-02-10 15:50
updated post :)

**Comment by stephenplusplus** [comment] 2017-02-10 16:30
Hmm, I wasn't able to reproduce using those versions. Might be worth trying the usual things, `rm -rf node_modules && npm cache clean && npm install`

@callmehiphop can you see if you can reproduce?

**Comment by stephenplusplus** [comment] 2017-02-14 15:27
@ohad-bpal are you still getting this issue?

**Comment by callmehiphop** [comment] 2017-02-14 16:37
@stephenplusplus missed the mention - but I can't reproduce this either.

**Comment by stephenplusplus** [comment] 2017-02-16 17:38
@ohad-bpal if you're still seeing this, let us know. Closing for now as it seems not to be a widespread issue.

**Closed by stephenplusplus** 2017-02-16 17:38 UTC
