### ISSUE TITLE
Extreme Latency when Using Google Cloud Functions and Cloud Datastore

### ISSUE THREAD

**Issue by richardowright** [GoogleCloudPlatform/google-cloud-node#2374] opened 2017-06-10 13:12 UTC
#### Environment details

  - OS: Google Cloud Functions
  - Region: US Central
  - google-cloud-node version: 1.0.2

#### Steps to reproduce
I experience high latency (~1 to 2 seconds) with pretty much every action. 

Simple example  (runs through bable prior to deploy) - 

```
static async addPerson() {
    try {
      const datastore = Datastore({
        projectId: projectId
      });
      const key = datastore.key('person');
      const person = {
        key: key,
        data: 
          [
            { name: 'last_name', value: 'Wright' },
			{ name: 'last_name_UPPER', value: 'WRIGHT' },
            { name: 'first_name', value: 'Richard' },
			{ name: 'first_name_UPPER', value: 'RICHARD' },
			{ name: 'email', value: 'mygmail@gmail.com' },
            { name: 'address_street', value: 'My Place', excludeFromIndexes: true },
            { name: 'address_city', value: 'City' },
            { name: 'address_state', value: 'State' },
            { name: 'address_zip', value: '12345' },
            { name: 'phone', value: '123.456.7890' },
            { name: 'date_of_birth', value: new Date(1901, 02, 03)},
            { name: 'create_time', value: new Date(Date.now()), excludeFromIndexes: true }
          ]
      };
      
      let saveResponse = await datastore.save(person);
      
      let person_id=saveResponse[0].mutationResults[0].key.path[0].id;
      return person_id;
    } catch (err) {
      console.log(err);
      return;
    }
  }
```

**Comment by stephenplusplus** [comment] 2017-06-10 13:26
Can you see if subsequent calls also have a lag? The first request has to sort out the authentication details, so it's known to be slower.

**Comment by richardowright** [comment] 2017-06-10 14:20
If I call the datastore API within the same function call, I do see a reduction in subsequent call time -

```
db_add_person: 1409.076ms
5668753656250368
db_add_person: 363.180ms
5645784439586816
db_add_person: 235.747ms
5637489247125504
```

I've also discovered that using a key file (i.e. creating a service account and specifying keyFilename) decreases the first call time from ~1.4 seconds to 0.85 s.  

However, I'm still at about 0.8s per HTTP call which is still quite high.

**Comment by stephenplusplus** [comment] 2017-06-12 12:40
> since when using cloud functions, the penalty is incurred on each http invocation the overhead is still very high (i.e. 0.8s per HTTP call).

Yes, unfortunately. I'll close the issue, as we can't do anything within the client library. If any ideas come to mind for how this can be addressed, feel free to discuss.

**Comment by ro-savage** [comment] 2017-08-07 10:45
@stephenplusplus - We are running into the same issue. Datastore and Functions seem like the perfect combination, paying only a per-request cost. However the latency is much too high to be usable in real-world.

As was mentioned, it is related to the Auth. 

This problem must be solvable, as other similar systems such as Lambda + DynamoDB don't under into this issue.

It seems unlikely to be implemented in node, but probably some setup on the function/lambda that is 'pre-authenticated' (AWS IAM roles?).

Who would be the correct team/repo to work on this issue?

**Comment by reco** [comment] 2017-08-28 15:36
@ro-savage we were/are using app engine with datastore. we also did run in to big issues with the latency of the datastore. would love to hear some updates @google-admin about this issue.

**Comment by ahume** [comment] 2017-09-26 23:05
A few weeks into development, we're finding Datastore to not be a viable solution for use in Functions due to the consistently poor performance on even very simple queries. 4000ms on first (authenticating request), and then 800-1200ms afterwards.

**Comment by bittlingmayer** [comment] 2017-10-02 14:04
Also hitting this problem, with the Google Translate API.  Consistently ca 800ms.

There must be a way to fix this, at least on subsequent requests, given that auth can be based on the project id, it's all internal to a single Google datacentre and so on.

**Comment by ignaciovazquez** [comment] 2017-10-03 04:44
We are also experiencing 60ms-200ms latencies on a lookup by key (runQuery is even worse) from GAE Flexible in node.

**Comment by stephenplusplus** [comment] 2017-11-06 17:07
*Also reported in #2727*

@lukesneeringer this seems to be a common problem. The most recent report shows 10 seconds spent on a query that should take in the tens of milliseconds. Worth considering, our Datastore API uses the REST endpoint. There is a GAPIC layer that we will likely convert to during our repo extraction.

**Comment by EJB3927** [comment] 2017-11-06 17:08
Thank you @stephenplusplus. I can confirm I'm having this issue with the following environment: 
  - OS: macOS Sierra
  - Node.js version: 7.10.0
  - npm version: 4.2.0
  - google-cloud/datastore version: 1.1.0

Additionally, I'm noticing the issue on Cloud Functions with the same node and NPM versions.

**Comment by lukesneeringer** [comment] 2017-11-06 21:18
If this is something that is fixed by switching to the gRPC transport we use elsewhere, then this should be a reasonably (~week or so) quick fix.

**Comment by ChrisBartonLC** [comment] 2017-11-08 16:47
We also have the same high latency issues mentioned by @ahume with CloudFunctions and Datastore

**Comment by ChrisBartonLC** [comment] 2017-11-08 16:57
I guess if you convert to gRPC then the Datastore comms will start having this problem like Spanner and PubSub #2438

**Comment by ChrisBartonLC** [comment] 2017-12-07 02:25
I get a significant reduction in latency in calls from CloudFunctions to Datastore by embedding a service account. For warm functions latency was previously several seconds (mostly around 2-3 seconds) and are now mostly 1 second with the occasional 2 seconds. These calls are a mixture of CRUD operations. 

FYI I am using AppEngine cron to trigger a job every minute to hit all functions several times in order to keep them warm. 

We have around 60 functions in all. Every function has a health mode where it immediately returns instead of calling Datastore and the latency of the functions when operating in this mode are around 200-400ms with the occasional 500-600ms.

Old code (without the 'at' prefix):
client = { datastore: require('google-cloud/datastore')() }

New code (without the 'at' prefix):
require('google-cloud/datastore')({ credentials: service_account })

The service account is encrypted with GCP KMS so I must load it and cache it prior to the function running so basically wrapping the entry point in a promise.

**Comment by ChrisBartonLC** [comment] 2017-12-07 02:35
Does anyone know what the expected latency of Datastore is? We are considering moving to Go and AppEngine (which we used before with AWS and DynamoDB) or will that have the same issues? Would it be better for us to look at using CloudSQL if we want low latency?

**Comment by ChrisBartonLC** [comment] 2017-12-10 04:10
Today I deployed our code to app engine flex using the same node.js version used by gcp functions. In both cases (same code) auth is an embedded service account decrypted (and cached) using GCP KMS.

Pings average around 250ms compared to 350ms in functions. However the latency is more erratic from functions with a % falling into the 500-1000ms window. So basically functions are only slightly slower but more erratic.

Reads from Datastore ape the pings results but erratic latency tends to be magnified. Data is attached.

[perf-appengine.txt](https://github.com/GoogleCloudPlatform/google-cloud-node/files/1545301/perf-appengine.txt)
[perf-fn.txt](https://github.com/GoogleCloudPlatform/google-cloud-node/files/1545302/perf-fn.txt)

**Comment by ro-savage** [comment] 2017-12-10 06:15
Just at side note to maintainers / google. We raised this issue in a few places including in person at Google Sydney and pretty much were told there is no solution and no eta.

We ended up leaving google cloud and moving to AWS. Not only was it must faster but it costs significantly less because all our functions run in under 100ms on AWS with Dynamo compared to multiple hundreds (sometimes 1-2s) with Google Cloud.

This issue is one of the things that kills the ability for people to use Cloud Functions and Datastore together on a production app.

**Comment by ChrisBartonLC** [comment] 2017-12-10 18:07
Thanks @ro-savage I was coming to the same conclusion. To be fair Datastore and DynamoDB are not drop-in replacements because Datastore has transactions which are occasionally very useful and help keep the code clean because you do not need to cope with in-consistent data where that can happen. DynamoDB is very very fast and has proper support for updating documents unlike Datastore where an update replaces the entire entity. I have used both extensively and would prefer Datastore if it were faster. Lambda is of course far ahead of functions which is unsurprising given that functions is beta. AWS support is incredible, I get AWS engineers phoning me to ask how they can help out.

**Comment by ChrisBartonLC** [comment] 2017-12-11 03:54
Just did the same tests but using App Engine Flex with Go 1.9.2 instead of Node.js (App Engine Flex and Functions) and latency for pings average around 250ms and reads 390ms. Both the pings and the read latency are much less erratic compared to Node.js (App Engine Flex and Functions). We are the other side of the world from the infra (but still on fiber) so it's the delta between the ping and read that is important not the absolute number. So we will stick with Datastore but just use Go and App Engine Flex. FYI it is easy to support both Functions and Node.js App Engine Flex.

Data is attached.
[
[perf-appengine-go.txt](https://github.com/GoogleCloudPlatform/google-cloud-node/files/1546472/perf-appengine-go.txt)
](url)

**Comment by stephenplusplus** [comment] 2017-12-11 20:33
I'm marking this as `blocked` as there are 2 places I can see that could be responsible:

1) Cloud Functions. Something in the environment doesn't interact quickly with something in the callstack. I would guess the auth layer (google-auth-library) or the transport layer (grpc).
2) Our library needs to use the GAPIC API. Currently, our library communicates with Datastore through the transport layer, gRPC, directly. gRPC exposes many knobs for configuration, but we are using the defaults that it provides. The GAPIC API stands between us and gRPC and changes some of those settings.

We are almost switched over to the GAPIC API. We are working on the final steps of splitting the Datastore code out from this repo and into its own. After that, it would be great if anyone with patience remaining could test it out for us.

If it doesn't have any effect, we will need to make sure this feedback gets noticed by the Cloud Functions team and we start a proper search for the problem.

**Comment by ChrisBartonLC** [comment] 2017-12-11 20:38
Happy to test when you're ready

**Comment by richardowright** [comment] 2017-12-11 20:44
Thanks. A few things I've found that might be relevant findings to help diagnose - 
- the first call from within the same function execution is slow; if I save multiple times in the same execution/call of/to the function, the time drops 
- using a key file (i.e. creating a service account and specifying keyFilename) decreases the first call time from ~1.4 seconds to 0.85 s.
- increasing the memory usage of the cloud function has a significant impact on timing

**Comment by ChrisBartonLC** [comment] 2017-12-11 21:01
We use --memory=1024MB in order to get a faster machine (as recommended in the docs). We  haven't tired any higher memory settings. 

We see similar behaviour to @richardowright and its important to note that the mean latency is not the only problem; some requests can still take multiple seconds even when auth is hardcoded to give a lower mean latency. Similar behaviour is seen in App Engine Flex with Node.js i.e. some requests take > 1 sec even though the mean for reads is lower ~ 600ms.

**Comment by ChrisBartonLC** [comment] 2017-12-14 02:06
I just did the same test against DynamoDB using a 1024MB Lambda behind API Gateway using Go and eawsy's aws-lambda-go-shim and the latency was ~490ms and pretty stable. This is all very rough and ready but seems there is no big difference between Go/AppEngine/Datastore compared to Go/API Gateway/Lambda/DynamoDB and so once Cloud Functions gets Go support I will be happy :)

[perf-lambda-go.txt](https://github.com/GoogleCloudPlatform/google-cloud-node/files/1557709/perf-lambda-go.txt)

**Comment by stephenplusplus** [comment] 2017-12-16 03:54
This issue was moved to https://github.com/googleapis/nodejs-datastore/issues/9.

**Closed by stephenplusplus** 2017-12-16 03:54 UTC
Labels: api: datastore, core, perf, status: blocked, type: backend

**Comment by lazharichir** [comment] 2018-01-13 22:06
Facing the very same issue with Google Cloud Functions and Firestore... First call takes several seconds, generally from 3 to 6 seconds. Subsequent calls half the latency. I have separate Functions talking to a MongoDB VM in Compute Engine, and the latency is < 1s, except on the first call where it's around 3-5 seconds.

I've moved some functions to AWS Lambda with DynamoDB where the latency is at most 1.5s, which is definitely doable in an end-user facing situation.... Sad.

**Comment by ChrisBartonLC** [comment] 2018-01-13 22:13
@lazharichir you should probably add your comment here https://github.com/googleapis/nodejs-datastore/issues/9 since this issue is closed

**Comment by ChrisBartonLC** [comment] 2018-01-13 22:17
@lazharichir you can significantly improve latency in AWS Lambda if you use a CloudWatch scheduled Lambda to keep your function warm

**Comment by koistya** [comment] 2018-02-26 12:23
So far I have ~500ms latency for a simple API endpoint. Do you have a suggestion how to trace it and find the cause of the issue?

https://firebase.reactstarter.com online demo + [source code](https://github.com/kriasoft/react-firebase-starter)

**Comment by karlbateman** [comment] 2018-05-11 16:09
Can someone confirm whether or not using gRPC makes a notable difference?

**Comment by richardowright** [comment] 2018-05-13 19:06
@karlbateman I'm seeing significant improvements with the latest version. For the function above which was taking ~800ms per call, I know see call times around 150 ms.

**Comment by richardowright** [comment] 2018-05-13 19:09
@koistya I'd post or look through https://stackoverflow.com/questions/tagged/google-cloud-functions. I took a quick look through the code, and it seems unrelated to cloud datastore.
