### ISSUE TITLE
PubSub: Unable to create a pull subscription to a topic where acknowledged messages are retained

### ISSUE THREAD

**Issue by braxtonb** [GoogleCloudPlatform/google-cloud-node#2639] opened 2017-10-01 00:01 UTC
#### Environment details

  - OS: macOS Sierra version 10.12.2
  - Node.js version: v8.2.1
  - npm version: 4.6.1
  - google-cloud-node version: 0.14.2

#### Steps to reproduce

  1. require `google-cloud`
  2. initialize pubsubClient
  3. create subscription to a topic with config option `retainAckedMessages` set to true (see code below)
  4. push 5 messages to a topic
  5. pull and acknowledge the 5 messages from the topic successfully the first time
  6. in a second attempt to pull the 5 messages again, 0 are retrieved
  7. get the metadata for the subscription created to the topic in step 3, and `retainAckedMessages` is set to false (and `messageRetentionDuration` is set to null even though it should default to 7 days)

Below is the code I use to create a subscription
```js
const PubSub = require('@google-cloud/pubsub');

const Keys = require('./json/pubsub-editor-keys');

const projectId = 'my-project-id';
let pubsubClient;
const subscriptionName = 'my-subscription-name';
const topicName = 'my-topic';

const initializePubSubClient = (client_email, private_key) => {
  const options = {
    projectId,
    credentials: {
      client_email,
      private_key
    }
  };
  pubsubClient = PubSub(options);
}

const createSubscription = (topic, name) => {
  const options = {
    retainAckedMessages: true
  };

  console.log('createSubscription called');

  pubsubClient
    .createSubscription(topic, name, options)
    .then((data) => {
      const subscription = data[0];
      const apiResponse = data[1];
      console.log('subscription', subscription);
      console.log('apiResponse', apiResponse);
    })
    .catch((err) => {
      console.log('error', err);
    });
}

initializePubSubClient(Keys.client_email, Keys.private_key);
createSubscription(topicName, subscriptionName);

```

- I would like to create a pull subscription to a topic where acknowledged messages are retained for a set amount of time. 
- I have tried accomplishing this by setting retainAckedMessages to true and leaving messageRetentionDuration as the default 7 days; however, I have not had success in initializing a subscription with those option values. 
- Regardless of the options I use to initialize the subscription, acknowledged messages are removed from the subscribed topic's stored messages.
- Related to #2240

**Comment by callmehiphop** [comment] 2017-10-01 15:28
@braxtonb Out of curiosity when you log out the subscription and response upon creation, do you see `retainAckedMessages` set initially? I ask because in my local testing it seems that the API is honoring the option.

**Comment by braxtonb** [comment] 2017-10-01 16:09
@callmehiphop Yes, when I log out the subscription and response upon creation I see `retainAckedMessages` set initially in the response. However, it is set to false.

Here's a sample response I see upon creation:

```json
{
  "metadata": {
    "name": "projects/my-project-id/subscriptions/my-subscription-name",
    "topic": "projects/my-project-id/topics/my-topic",
    "pushConfig": { "pushEndpoint": "", "attributes": {} },
    "ackDeadlineSeconds": 10,
    "retainAckedMessages": false,
    "messageRetentionDuration": null,
    "labels": {} 
  }
}
```

**Comment by callmehiphop** [comment] 2017-10-02 14:46
I can't actually reproduce this locally, could you try testing against the latest version (0.14.3) and see if your issue still persists?

Also, after creating your subscription have you tried setting `retainAckMessages` using `setMetadata`? Do you get any errors or is it the same result?

**Comment by braxtonb** [comment] 2017-10-02 15:46
I have tested against the latest version (0.14.3) and the issue persists.

After creating the subscription I have tried setting `retainAckedMessages` using `setMetadata` and I get errors.

Below is the code I use to set the metadata

```js
```

**Comment by callmehiphop** [comment] 2017-10-02 18:46
@jganetsk is `retainAckedMessages` still honored? It's documented in our [local proto files](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/pubsub/protos/google/pubsub/v1/pubsub.proto#L362). However I've noticed it is missing from the [upstream docs](https://cloud.google.com/pubsub/docs/reference/rpc/google.pubsub.v1#google.pubsub.v1.Subscription).

**Comment by callmehiphop** [comment] 2017-10-02 19:11
@braxtonb I've just been informed that `retainAckedMessages` is still an Alpha feature and is not yet generally available. So what you are experiencing appears to be the expected behavior. I'm going to close this issue, but I will comment on it if I learn any new info.

**Closed by callmehiphop** 2017-10-02 19:11 UTC
Labels: api: pubsub
