### ISSUE TITLE
`topic.exists` method does not resolve the promise but is pending indefinitely

### ISSUE THREAD

**Issue by hansman** [GoogleCloudPlatform/google-cloud-node#1957] opened 2017-02-02 19:37 UTC
Running `@google-cloud/pubsub@0.7.1`, the `topic.exists` method does not resolve the promise but is pending indefinitely. This is not the case in `@google-cloud/pubsub@0.6.2`.

#### Environment details

  - OS:
  - Node.js version: v5.12.0
  - npm version: 4.0.3
  - @google-cloud/pubsub@0.7.1

#### Steps to reproduce

```
pubsubClient.topic('test').exists()
Promise { <pending> }
> pubsubClient.topic('test').exists().then(console.log)
Promise { <pending> }
```

**Comment by stephenplusplus** [comment] 2017-02-04 17:16
This is likely a duplicate of #1946. Please follow along there. Thank you and sorry for the trouble.

**Closed by stephenplusplus** 2017-02-04 17:16 UTC
