### ISSUE TITLE
pubsub: don't work in cloud function (TypeError: message.encode(...).finish is not a function at BundleDescriptor.getByteLength)

### ISSUE THREAD

**Issue by jsididris** [GoogleCloudPlatform/google-cloud-node#2717] opened 2017-11-02 15:54 UTC
#### Environment details

  - OS: / (Google Cloud Function)
  - Node.js version: Node v6.11.1
  - npm version: /
  - google-cloud-node version: I'm using `google-cloud/pubsub` version `0.14.6`

#### Steps to reproduce
I have created 2 Cloud Functions : 

- one is trigered by HTTP and publishing in channel `event` 
- the second is trigered by pub/sub and subscribing to the `event` channel

<img width="792" alt="capture d ecran 2017-11-02 a 16 51 52" src="https://user-images.githubusercontent.com/27036652/32335890-2cdd0f36-bfee-11e7-80fc-a9a1f26e3351.png">

In my first function, i'm using the example code provided to publish to my `event` channel like that : 

```js
function firstFunction(req, res) {
    var pubsub = require('@google-cloud/pubsub');
    var pubsubClient = pubsub();
    var topic = pubsubClient.topic('event');
    var publisher = topic.publisher();
    var message = new Buffer('New message!');

    publisher.publish(message, function (err, messageId) {
        console.log("err", err);
        console.log("messageId", messageId);
        res.json({messageId});
    });
}

exports.firstFunction = firstFunction;
```

I deploy it in Google Cloud, and try my Cloud Function by call it with http, but in the StackDriver logs I can see an error when publishing the message : 

> err TypeError: message.encode(...).finish is not a function at BundleDescriptor.getByteLength [as byteLengthFunction] (/user_code/node_modules/@google-cloud/pubsub/node_modules/google-gax/lib/grpc.js:262:36) at /user_code/node_modules/@google-cloud/pubsub/node_modules/google-gax/lib/bundling.js:338:38 at Array.forEach (native) at BundleExecutor.schedule (/user_code/node_modules/@google-cloud/pubsub/node_modules/google-gax/lib/bundling.js:337:16) at /user_code/node_modules/@google-cloud/pubsub/node_modules/google-gax/lib/bundling.js:474:20 at Canceller.call (/user_code/node_modules/@google-cloud/pubsub/node_modules/google-gax/lib/api_callable.js:110:19) at Bundleable.call (/user_code/node_modules/@google-cloud/pubsub/node_modules/google-gax/lib/bundling.js:473:12) at /user_code/node_modules/@google-cloud/pubsub/node_modules/google-gax/lib/api_callable.js:356:17 at process._tickDomainCallback (internal/process/next_tick.js:135:7)

Note that 2 days ago it's worked perfectly. I had managed to deploy and communicate by pub / sub between my Cloud Functions, but today noticing that it was not working I went back to the basic example and even there it does not work ..

**Comment by stephenplusplus** [comment] 2017-11-02 16:36
Thanks for coming to report the issue. I am going to consider this a duplicate of #2699. I'll tag you over there so you can follow along with the progress. For now, pinning your dependency to `@google-cloud/pubsub@0.14.2` seems to be a temporary solution.

**Closed by stephenplusplus** 2017-11-02 16:36 UTC
